### ISSUE TITLE
License

### ISSUE THREAD

**Issue by smaresca** [marcusbotacin/BranchMonitoringProject#2]
Thank you for sharing this very interesting project publicly!

Would you be willing to offer the code under MIT, BSD, Apache, Mozilla, or LGPL licenses?  At the moment it is protected by your copyright, but use in other research/projects may not be possible without an explicit license

Thanks!

**Comment by marcusbotacin** [comment]
I had forgotten. MIT license added.

**Comment by smaresca** [comment]
Perfect, thank you
